const EXT_CONFIG_SECTION_NAME = "banner-comments";
const FIGLET_H_LAYOUT_CONFIG_KEY = "figlet.horizontalLayout";
const FIGLET_V_LAYOUT_CONFIG_KEY = "figlet.verticalLayout";
const WIDTH_CONFIG_KEY = "figlet.width";
const WHITESPACEBREAK_CONFIG_KEY = "figlet.whitespaceBreak";
const EXCLUDED_LANGUAGE_IDS = [ "plaintext" ];
const FIGLET_MIN_WIDTH = 10;

export {
	EXT_CONFIG_SECTION_NAME,
	FIGLET_H_LAYOUT_CONFIG_KEY,
	FIGLET_V_LAYOUT_CONFIG_KEY,
	EXCLUDED_LANGUAGE_IDS,
	WIDTH_CONFIG_KEY,
	WHITESPACEBREAK_CONFIG_KEY,
	FIGLET_MIN_WIDTH
};
